<?php 
define('qE1Imp','queueE1Import');
define('qE1Grab','queueE1Grabber');

function e1_entity_info(){
    $entities = array();
    $entities['e1_realty'] = array(
        'label' => t('e1.realty Entity'),
        'entity class' => 'Entity',
        'controller class' => 'EntityAPIController',
        'views controller class' => 'EntityDefaultViewsController',
        'base table' => 'e1_queue',
        'fieldable' => FALSE,
        'entity keys' => array(
            'id' => 'e1rid',
            'label' => 'e1. Realty ID',
        ),
        'bundles' => array(),
        'label callback' => 'e1_get_originalId', 
        'uri callback' => 'e1_uri',
        'access callback' => 'access content',
        'module' => 'e1',
    );
    return $entities;
}

function e1_get_originalId($entity_type, $entity){
    return $entity->e1id;
}

function addHtmlParser(){
    include_once('/home/drupal/git/pspider/lib/simple_html_dom_parser.php');    
}

function e1_menu(){
    $items = array();
    $items['e1/test'] = array(                                                                                                                        
        'title' => 'Queue test: Insert and remove',                                                                                                                      
        'page callback' => 'e1_import',                                                                                                                               
        'access callback' => TRUE,                                                                                                                                          
    );     
    return $items;
}

function e1_queueAddFromE1List(){
    //Add id's from e1List
    addHtmlParser();
    $pageCount = 10;
    $colors = array('#dddddd','#FFF3D7');                                                                                                                                   
    $rez = array();
    for($i=0;$i<$pageCount;$i++){                                                                                                                                           
        $html = file_get_html('http://www.e1.ru/business/realty/index.php?ot=4&bt=1&nb=0&p='.$i.'&sb=8&ob=2');
        //$rez = array();                                                                                                                                                       
        foreach($colors as $color)                                                                                                                                              
            foreach($html->find('tr[bgcolor='.$color.']') as $tr)                                                                                                               
                foreach($tr->find('td') as $td){                                                                                                                        
                    $ids = array();                                                                                                                                             
                    preg_match('/^([0-9]{7,8})*/',strip_tags(trim(str_replace('&nbsp;','',iconv('cp1251','utf-8',$td->children(0)->children(0)->href)))),$ids);                 
                    $rez[] = $ids[0];                                                                                                                                           
                    break;                                                                                                                                                      
                }                                                                                                                                                               
        //sleep(100);                                                                                                                                                           
    }
    $cnt = count($rez); 

    //Add grabbered content to Queue
    $queue = DrupalQueue::get(qE1Imp);
    
    foreach($rez as $eGrub) 
        $queue->createItem(array('url'=> 'http://www.e1.ru/business/realty/'.$eGrub.'.html','e1id' => $eGrub));
    
    if($cnt>0)                                                                                                                                                             
        watchdog('E1_Spider', 'grabbered '.$cnt);                                                                                                                                                                                                                                                                             
}

//Add from E1 url of uniq realty URL's 
function e1_cron(){
    e1_queueAddFromE1List();
}
//Create queue && timeout
function e1_cron_queue_info(){
  $queues = array();
  $queues[qE1Imp] = array(
    'worker callback' => 'e1_import', 
    'time' => 60, 
  );
  $queues[qE1Grab] = array(
    'worker callback' => 'e1_grabber', 
    'time' => 60, 
  );
  return $queues;
}


//GET from Queue to entity_converted 
function e1_import($url){
    //create queue
    //$queue = DrupalQueue::get(qE1Imp);                                                                                                       
    //$queue->createQueue(); 
    //add 1 item
   /* 
    $query = new EntityFieldQuery();

$query->entityCondition('entity_type', 'e1_realty')
  ->propertyCondition('original', $url['e1id']);
    $result = $query->execute();
   */
    $e1id = (empty($url['id'])?'4426792':$url['id']);
    $e1url= (empty($url['url'])?'http://www.e1.ru/business/realty/4426792.html':$url['id']);
    addHtmlParser();
    $html = file_get_html($e1url);                                                                                                                                 
    $hds = array('null1'=>'Количество смежных комнат:',                                                                                                                          
            'field_rooms'=>'Кол-во комнат в квартире:',                                                                                                                                
            'field_yardage'=>'Общая площадь, кв.м.',                                                                                                                                     
            'field_price'=>'Цена:',                                                                                                                                                    
            'Срок сдачи:',                                                                                                                                              
            'Коммунальные платежи:',                                                                                                                                    
            'Адрес:',                                                                                                                                                   
            'Последнее изменение:',                                                                                                                                     
            'Срок публикации, до:',                                                                                                                                     
            'Этаж:',                                                                                                                                                    
            'Сан узел:',                                                                                                                                                
            'Мебель:',                                                                                                                                                  
            'Телефон:',                                                                                                                                                 
            'Лоджия:',                                                                                                                                                  
            'Город:',                                                                                                                                                   
            'Район:',                                                                                                                                                   
            'Контактное лицо:',                                                                                                                                         
            'Телефон:',                                                                                                                                                 
            'Дополнительные сведения:'                                                                                                                                  
        ); 
    
    foreach($html->find('body table tbody tr td table tbody tr td table tbody') as $tbody)
        foreach($tbody->find('tr') as $tr){                                                                                                                             
            $need = '';                                                                                                                                                 
            foreach($tr->find('td') as $td){                                                                                                                            
                $value = strip_tags(trim(str_replace('&nbsp;',' ',iconv('cp1251','utf-8',$td->plaintext))));                                                            
                 if(in_array($value,$hds))                                                                                                                              
                    $need = $value;                                                                                                                                     
                elseif(!empty($need))                                                                                                                                   
                    $rez[$need][] = $value;                                                                                                                             
            }                                                                                                                                                           
        }                                                                                                                                                               
                                                                                                                                                                       
    //zabiraem opisanie                                                                                                                                                 
    foreach($html->find('body table tbody tr td table tbody') as $tbody){                                                                                               
        $need = '';                                                                                                                                                     
            foreach($tbody->find('tr') as $tr)                                                                                                                          
                    foreach($tr->find('td') as $td){                                                                                                                    
                            $value = strip_tags(trim(str_replace('&nbsp;',' ',iconv('cp1251','utf-8',$td->plaintext))));                                                
                             if(in_array($value,$hds)&&empty($rez[$value]))                                                                                             
                                    $need = $value;                                                                                                                     
                            elseif(!empty($need))                                                                                                                       
                                    $rez[$need][] = $value;                                                                                                             
                    }                                                                                                                                                   
    }
    unset($html);
    print_r($rez);
    die();
    $newNode = array();
    $newNode['type'] = 'flats';
    $newNode['title'] = $e1url;
    
    $qp = new StdClass();                                                                                                                                       
    $qp->type = 'equipment';                                                                                                                                    
    node_object_prepare($qp);                                                                                                                                   
    $qp->nid = 0;                                                                                                                                               
    
    watchdog('E1_Grubber', 'Try to grab '.$url['url']);
    $nd = node_load(30001);
    $nd->body .= $url['url'];
    node_save($nd);
}

function e1_grabber($in){
    
    
    
    
}